from copy import deepcopy
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DFME_DIR = PROJECT_ROOT / "dfme"
MATLAB_ROOT = PROJECT_ROOT / "dfme_matlab"
RESULTS_DIR = PROJECT_ROOT / "topo_latent_blackbox" / "results"


SYSTEM_CONFIGS = {
    14: {
        "input_dim": 54,
        "data_dir": MATLAB_ROOT / "FDIA_Dataset_case14",
        "oracle_ckpt": DFME_DIR / "checkpoint" / "oracle_case14_resmlp.pt",
    },
    30: {
        "input_dim": 112,
        "data_dir": MATLAB_ROOT / "FDIA_Dataset_case30",
        "oracle_ckpt": DFME_DIR / "checkpoint" / "oracle_case30_resmlp.pt",
    },
    118: {
        "input_dim": 490,
        "data_dir": MATLAB_ROOT / "FDIA_Dataset_case118",
        "oracle_ckpt": DFME_DIR / "checkpoint" / "oracle_case118_resmlp.pt",
    },
}


def resolve_system_config(system_id: int, data_dir: str = "", input_dim: int = 0) -> dict:
    if system_id not in SYSTEM_CONFIGS:
        raise ValueError(f"Unsupported IEEE system: {system_id}")
    cfg = deepcopy(SYSTEM_CONFIGS[system_id])
    if data_dir:
        cfg["data_dir"] = Path(data_dir)
    if input_dim > 0:
        cfg["input_dim"] = int(input_dim)
    return cfg


SYSTEM_ATTACK_PRESETS = {
    "manual": {},
    "simple_mainline_v1": {
        14: {
            "attack_mode": "region_search",
            "region_size": 5,
            "anchor_size": 2,
            "region_candidates": 3,
            "anchor_pool_size": 6,
            "hierarchical_probe": False,
            "initial_probe_region_topk": 0,
            "probe_expand_improvement_ratio": 0.0,
            "region_proposal_mode": "default",
            "probe_directions": 2,
            "probe_scale_ratio": 0.35,
            "population": 10,
            "rounds": 20,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "detector_feedback_region": False,
            "adaptive_query_budget": False,
            "structured_search_directions": False,
            "state_basis_search": False,
            "state_bandit_search": False,
            "measurement_delta_l2_ratio_cap": 0.20,
            "fdia_preserve_weight": 2.0,
            "fdia_state_projection_min": 0.55,
            "fdia_measurement_projection_min": 0.0,
            "fdia_offsupport_max": 1.0,
            "fdia_state_penalty_weight": 1.0,
            "fdia_measurement_penalty_weight": 0.0,
            "fdia_offsupport_penalty_weight": 0.0,
            "measurement_suppression_strength": 0.0,
            "injection_scale": 0.88,
            "flow_scale": 1.0,
            "leverage_suppression": 0.10,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "hierarchical_probe": False,
            "initial_probe_region_topk": 0,
            "probe_expand_improvement_ratio": 0.0,
            "region_proposal_mode": "default",
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 8,
            "rounds": 20,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "detector_feedback_region": False,
            "adaptive_query_budget": False,
            "structured_search_directions": True,
            "structured_direction_count": 8,
            "state_basis_search": True,
            "state_bandit_search": True,
            "state_basis_dim": 12,
            "bandit_direction_samples": 4,
            "bandit_momentum": 0.85,
            "bandit_exploration_ratio": 1.10,
            "bandit_warmup_rounds": 6,
            "measurement_delta_l2_ratio_cap": 0.35,
            "fdia_preserve_weight": 2.0,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.0,
            "fdia_offsupport_max": 1.0,
            "fdia_state_penalty_weight": 1.0,
            "fdia_measurement_penalty_weight": 0.0,
            "fdia_offsupport_penalty_weight": 0.0,
            "measurement_suppression_strength": 0.0,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.25,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
    "scale_adaptive_mainline_v1": {
        14: {
            "attack_mode": "region_search",
            "region_size": 2,
            "anchor_size": 2,
            "region_candidates": 3,
            "anchor_pool_size": 8,
            "probe_directions": 2,
            "probe_scale_ratio": 0.35,
            "population": 12,
            "rounds": 24,
            "probe_channel_shaping_only": True,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "adaptive_query_budget": False,
            "score_stagnation_early_stop": False,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        30: {
            "attack_mode": "region_search",
            "region_size": 8,
            "anchor_size": 2,
            "region_candidates": 6,
            "anchor_pool_size": 8,
            "probe_directions": 3,
            "probe_scale_ratio": 0.35,
            "population": 12,
            "rounds": 24,
            "probe_channel_shaping_only": True,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 8,
            "rounds": 24,
            "state_basis_search": True,
            "state_bandit_search": False,
            "state_basis_dim": 12,
            "adaptive_query_budget": True,
            "easy_population": 6,
            "easy_rounds": 6,
            "easy_probe_improvement_ratio": 0.08,
            "measurement_delta_l2_ratio_cap": 0.40,
            "fdia_preserve_weight": 4.0,
            "fdia_backbone_lock_ratio": 0.20,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.45,
            "fdia_offsupport_max": 0.60,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.30,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
    "layered_active_mainline_v1": {
        14: {
            "attack_mode": "layered_region_search",
            "region_size": 2,
            "anchor_size": 2,
            "region_candidates": 3,
            "anchor_pool_size": 8,
            "probe_directions": 2,
            "probe_scale_ratio": 0.35,
            "population": 12,
            "rounds": 24,
            "active_set_sizes": [2, 4, 6, 8, 13],
            "layered_stage_rounds": 4,
            "layered_final_rounds": 8,
            "probe_channel_shaping_only": True,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "adaptive_query_budget": False,
            "score_stagnation_early_stop": False,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "layered_region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 8,
            "rounds": 24,
            "active_set_sizes": [16, 117],
            "layered_stage_rounds": 1,
            "layered_final_rounds": 20,
            "state_basis_search": True,
            "state_bandit_search": False,
            "state_basis_dim": 12,
            "adaptive_query_budget": True,
            "easy_population": 6,
            "easy_rounds": 6,
            "easy_probe_improvement_ratio": 0.08,
            "measurement_delta_l2_ratio_cap": 0.40,
            "fdia_preserve_weight": 4.0,
            "fdia_backbone_lock_ratio": 0.20,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.45,
            "fdia_offsupport_max": 0.60,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.30,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
    "one_shot_mainline_v1": {
        14: {
            "attack_mode": "region_search",
            "region_size": 2,
            "anchor_size": 2,
            "region_candidates": 1,
            "anchor_pool_size": 8,
            "probe_directions": 1,
            "probe_scale_ratio": 0.35,
            "population": 12,
            "rounds": 24,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "feedback_keep_probe_best_incumbent": False,
            "adaptive_query_budget": True,
            "score_stagnation_early_stop": True,
            "probe_channel_shaping_only": True,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "single_active_region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 8,
            "rounds": 24,
            "single_active_size": 64,
            "state_basis_search": True,
            "state_bandit_search": False,
            "state_basis_dim": 12,
            "adaptive_query_budget": True,
            "easy_population": 6,
            "easy_rounds": 6,
            "easy_probe_improvement_ratio": 0.08,
            "measurement_delta_l2_ratio_cap": 0.40,
            "fdia_preserve_weight": 4.0,
            "fdia_backbone_lock_ratio": 0.20,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.45,
            "fdia_offsupport_max": 0.60,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.30,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
    "deterministic_mainline_v1": {
        14: {
            "attack_mode": "region_search",
            "region_size": 2,
            "anchor_size": 2,
            "region_candidates": 1,
            "anchor_pool_size": 8,
            "probe_directions": 1,
            "probe_scale_ratio": 0.35,
            "population": 4,
            "rounds": 24,
            "step_ratio": 0.50,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "adaptive_query_budget": True,
            "score_stagnation_early_stop": True,
            "probe_channel_shaping_only": True,
            "structured_search_directions": True,
            "structured_direction_count": 4,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "single_active_region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 8,
            "rounds": 24,
            "single_active_size": 64,
            "state_basis_search": True,
            "state_bandit_search": False,
            "state_basis_dim": 12,
            "adaptive_query_budget": True,
            "easy_population": 6,
            "easy_rounds": 6,
            "easy_probe_improvement_ratio": 0.08,
            "measurement_delta_l2_ratio_cap": 0.40,
            "fdia_preserve_weight": 4.0,
            "fdia_backbone_lock_ratio": 0.20,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.45,
            "fdia_offsupport_max": 0.60,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.30,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
    "physics_subspace_zoo_v1": {
        14: {
            "attack_mode": "region_search",
            "region_size": 2,
            "anchor_size": 2,
            "region_candidates": 1,
            "anchor_pool_size": 8,
            "probe_directions": 1,
            "probe_scale_ratio": 0.35,
            "population": 4,
            "rounds": 24,
            "step_ratio": 0.50,
            "region_budget_topk": 1,
            "region_budget_explore_rounds": 0,
            "feedback_loop": False,
            "adaptive_query_budget": True,
            "score_stagnation_early_stop": True,
            "probe_channel_shaping_only": True,
            "state_subspace_pgzoo": True,
            "state_basis_dim": 4,
            "pgzoo_probe_pairs": 2,
            "pgzoo_alpha_ratio": 1.0,
            "pgzoo_momentum": 0.80,
            "pgzoo_line_candidates": 3,
            "pgzoo_structured_covariance": True,
            "pgzoo_physical_preconditioner": True,
            "pgzoo_covariance_gamma": 0.60,
            "pgzoo_covariance_ridge": 1e-3,
            "pgzoo_preconditioner_ridge": 0.08,
            "measurement_suppression_strength": 0.35,
            "injection_scale": 0.90,
            "flow_scale": 1.0,
            "leverage_suppression": 0.15,
            "min_channel_scale": 0.72,
            "early_stop_on_success": True,
        },
        118: {
            "attack_mode": "single_active_region_search",
            "region_size": 117,
            "anchor_size": 3,
            "region_candidates": 1,
            "anchor_pool_size": 3,
            "probe_directions": 1,
            "probe_scale_ratio": 0.25,
            "population": 12,
            "rounds": 40,
            "single_active_size": 117,
            "adaptive_query_budget": True,
            "easy_population": 6,
            "easy_rounds": 6,
            "easy_probe_improvement_ratio": 0.08,
            "state_subspace_pgzoo": True,
            "state_basis_dim": 12,
            "pgzoo_probe_pairs": 4,
            "pgzoo_alpha_ratio": 1.0,
            "pgzoo_momentum": 0.80,
            "pgzoo_line_candidates": 3,
            "pgzoo_structured_covariance": True,
            "pgzoo_physical_preconditioner": True,
            "pgzoo_covariance_gamma": 0.75,
            "pgzoo_covariance_ridge": 1e-3,
            "pgzoo_preconditioner_ridge": 0.10,
            "measurement_delta_l2_ratio_cap": 0.40,
            "fdia_preserve_weight": 4.0,
            "fdia_backbone_lock_ratio": 0.20,
            "fdia_state_projection_min": 0.45,
            "fdia_measurement_projection_min": 0.45,
            "fdia_offsupport_max": 0.60,
            "injection_scale": 0.82,
            "flow_scale": 1.0,
            "leverage_suppression": 0.30,
            "min_channel_scale": 0.60,
            "early_stop_on_success": True,
        },
    },
}


def resolve_attack_preset(preset_name: str, system_id: int) -> dict:
    if preset_name not in SYSTEM_ATTACK_PRESETS:
        raise ValueError(f"Unsupported attack preset: {preset_name}")
    preset = SYSTEM_ATTACK_PRESETS[preset_name]
    return deepcopy(preset.get(system_id, {}))
